"""Generate docs/Warden_Blueprint.md from the code.

The blueprint is the locked spec: names, roles, controls, tools, thresholds,
prices. Every one already lives in constants.py, so writing them by hand would
make a second source of truth that drifts. Prose lives here, tables are
generated. Run after any change to constants.py.

    python scripts/build_blueprint.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

from warden import constants as C  # noqa: E402


def table(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for row in rows:
        out.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(out)


def build() -> str:
    mpath = ROOT / "results/manifest.json"
    m = json.loads(mpath.read_text(encoding="utf-8")) if mpath.exists() else None
    p = []
    add = p.append

    add("# {}, {} blueprint".format(C.PROJECT_NAME, C.PROJECT_SUBTITLE))
    add("")
    add("> Generated by `scripts/build_blueprint.py` from `src/warden/constants.py`. "
        "Do not edit by hand: change the constant and rebuild.")
    add("")
    add("{} | {}".format(C.BRAND, C.BRAND_SITE))
    add("")
    add("{}".format(C.CREDIT_LINE))
    add("")
    add("{} Built by {}.".format(C.SERIES_POSITION, C.OWNER))
    add("")

    add("## The problem")
    add("")
    add("{} runs the {}, a chatbot over HR files with an agent that can act. "
        "It shipped with no security review. Three things are wrong:".format(
            C.COMPANY, C.ASSISTANT_NAME))
    add("")
    add("- Outsiders can talk to the model. Candidate CVs and web pages are read "
        "into the prompt, so a hidden instruction is an instruction to the app.")
    add("- Retrieval ignores who is asking. Everyone gets the same answers, so "
        "the assistant is a way round the HR system's permissions.")
    add("- The agent can act, and nothing checks the action. An injected "
        "instruction can email a file out or change pay.")
    add("")
    add("Warden is the gateway in front of that app. The app is not changed.")
    add("")

    add("## The eight controls")
    add("")
    add(table(["id", "control", "what it does"],
              [[cid, "`{}`".format(k), purpose] for cid, k, purpose in C.CONTROLS]))
    add("")
    add("Order is load bearing. Cheap checks run first. The controls that stop "
        "harm rather than flag it (W5 permission-aware retrieval, W8 the tool "
        "policy) run where they can actually intervene.")
    add("")

    add("## Roles and permissions")
    add("")
    add(table(["role", "clearance summary"], [
        [C.ROLE_EMPLOYEE, "own record and public policies only"],
        [C.ROLE_LINE_MANAGER, "own team's payroll and contracts, plus public"],
        [C.ROLE_HR_ADVISOR, "all contracts and CVs, plus public"],
        [C.ROLE_PAYROLL, "all payroll and contracts, plus public"],
        [C.ROLE_RECRUITER, "CVs only, plus public"]]))
    add("")
    add("Access is by group, deny by default. Trust is a separate idea from "
        "sensitivity: a CV is low sensitivity and completely untrusted.")
    add("")

    add("## The agent's tools")
    add("")
    add(table(["tool", "changes the world?", "policy"], [
        [C.TOOL_LOOKUP, "no", "any signed-in staff"],
        [C.TOOL_WEB, "no", "any signed-in staff; result is untrusted"],
        [C.TOOL_EMAIL, "yes", "company domain only, else block"],
        [C.TOOL_PAYROLL, "yes", "payroll role; ask a human over GBP {}, block over GBP {:,}".format(
            C.PAYROLL_ASK_ABOVE_GBP, C.PAYROLL_BLOCK_ABOVE_GBP)]]))
    add("")

    add("## Thresholds")
    add("")
    add(table(["setting", "value"], [
        ["injection score to block (W2)", C.CLASSIFIER_THRESHOLD],
        ["retrieval top k", C.RETRIEVAL_TOP_K],
        ["payroll change needs a human above", "GBP {}".format(C.PAYROLL_ASK_ABOVE_GBP)],
        ["payroll change blocked above", "GBP {:,}".format(C.PAYROLL_BLOCK_ABOVE_GBP)],
        ["CI fails if breach rate above", C.REDTEAM_MAX_SUCCESS_RATE],
        ["CI fails if correct answers below", C.UTILITY_MIN_CORRECT_RATE]]))
    add("")

    add("## Synthetic data")
    add("")
    if m:
        add(table(["item", "count"], [
            ["employees", m["corpus"]["employees"]],
            ["candidates", m["corpus"]["candidates"]],
            ["documents", m["corpus"]["documents"]],
            ["attacks (dev + held-out)", m["probe_counts"]["total"]]]))
    else:
        add("_Run `python scripts/run_all.py` first to fill in the counts._")
    add("")
    add("Every identifier is fictional: `.example` domains, the `{}` NI specimen "
        "prefix, the card test issuer range, the Ofcom drama phone range.".format(
            C.NINO_PREFIX))
    add("")

    add("## Stack")
    add("")
    add(table(["piece", "role", "cost"], [
        ["Cloudflare Workers", "the gateway at the edge", "free tier"],
        ["Workers AI: Llama Guard 3", "harm check (W3)", "usage"],
        ["Workers AI: {}".format(C.CF_MODEL_CHAT.split('/')[-1]), "the chat model", "usage"],
        ["Workers AI: bge embeddings", "retrieval vectors", "usage"],
        ["Vectorize", "vector store with permission filter (W5)", "free tier"],
        ["AI Gateway", "logs, caching, rate limits", "free"],
        ["Prompt Guard 2 on Oracle VM", "injection classifier (W2)", "always free"],
        ["Presidio", "PII detection (W4, W6)", "open source"]]))
    add("")
    add("Prices checked {}. Budget {} to {} USD a month.".format(
        C.DOCS_CHECKED_DATE, C.MONTHLY_BUDGET_USD_LOW, C.MONTHLY_BUDGET_USD_HIGH))
    add("")
    add("---")
    add("")
    add(C.RIGHTS_LINE)
    add("")
    return "\n".join(p)


def main() -> int:
    out = ROOT / "docs/Warden_Blueprint.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build(), encoding="utf-8")
    print("Wrote {}".format(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
